language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jp/frontend-kubernetes -f Dockerfile.dev .

script:
  - docker run -e CI=true jp/frontend-kubernetes npm run test
