version: '3'
services:
  web:
    build:
      context: . # path where to check for building
      dockerfile: Dockerfile.dev # look into the context for this file
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # do not map "node_modules" inside the container since we have all node's dependencies only in the container, not also locally
      - .:/app # map everything from the current directory to the "app" folder inside the container, including the source code files.
